name: Build CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Go Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Go 1.21.x
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
        cache-dependency-path: |
          go.mod
          go.sum

    - name: Build Go Code
      run: |
        go build -v cmd/nutanix-exporter/main.go
