name: Build CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Go Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Go Setup
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'
        cache-dependency-path: |
          go.mod
          go.sum

    - name: Go Build
      run: |
        go build -v cmd/nutanix-exporter/main.go
